### PR TITLE
hw/ssi: update trans_done

### PR DESCRIPTION
**Pull request by amirgon**
Fixes https://github.com/espressif/qemu/issues/39

### CODE REVIEW

**Comment by igrr** [comment]
@amirgon thank you for the PR and sorry for the Github Action closing it. The "repo lockdown" is an upstream QEMU feature which we haven't deleted in this fork. I have disabled this workflow now.
On the topic of the PR, could you please describe the use case where this change is necessary? This is so that we can add a regression test to cover that use case. If your use case can be tested with one of IDF examples, it would be the easiest option.

**Comment by amirgon** [comment]
> could you please describe the use case where this change is necessary?

I'm attempting to emulate ESP32+ILI9341 device on QEMU in order to run [Micropython + LVGL](https://github.com/lvgl/lv_micropython).  
These are really just the first few steps to see if I can connect an ILI9341 display device in QEMU to your SPI master emulation.  
In this process when I suspect some wrong/missing functionality I'm opening an issue to start a discussion.

In this specific case I'm trying to initialize a SPI display driver which calls `spi_device_polling_transmit` at some point and gets stuck, as described in https://github.com/espressif/qemu/issues/39

**Comment by igrr** [comment]
I see, thanks for the explanation! I think you may run into more parts of SPI master which aren't implemented in QEMU, like for example DMA transfers. If you end up implementing more things, please feel free to push additional changes to the PR.

Regarding display emulation, you might also be interested in this display emulation code written by @a159x36: https://github.com/a159x36/qemu/commit/ad9de5f25ca80e8724d5714a6dbecff994ceb8ce. (That fork also seems to include Wi-Fi emulation, which is another awesome feature!)

**Comment by amirgon** [comment]
> I think you may run into more parts of SPI master which aren't implemented in QEMU, like for example DMA transfers.

I will definitely need DMA transfers.

> If you end up implementing more things, please feel free to push additional changes to the PR.

Sure.

> Regarding display emulation, you might also be interested in this display emulation code written by @a159x36: [a159x36@ad9de5f](https://github.com/a159x36/qemu/commit/ad9de5f25ca80e8724d5714a6dbecff994ceb8ce). (That fork also seems to include Wi-Fi emulation, which is another awesome feature!)

Wow that's one big commit! It seems to also implement DMA transfers on SPI, and attach `st7789v` to the SPI device, exactly what I planned to do for ili9341... 
That's very interesting, thank you very much for sharing this with me.

Do you have any plans to integrate @a159x36's (@dzo) changes (wifi, spi dma etc.) into Espressif QEMU port?

**Comment by igrr** [comment]
Have picked your fix into https://github.com/espressif/qemu/releases/tag/esp-develop-20220802 release, thanks again!

**Pull request closed without merging**
